#!/bin/sh

UPTIME_DAYS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 / 86400)
UPTIME_HOURS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 / 3600)
UPTIME_MINUTES=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 % 3600 / 60)

cat << EOF
              Name: `hostname`
              Uptime: $UPTIME_DAYS days, $UPTIME_HOURS hours, $UPTIME_MINUTES minutes

              CPU: `cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d':' -f2`
	      GPU: `sudo lshw -C video | grep 'product' | head -1 | cut -d':' -f2`
              Memory: `free -g | head -n 2 | tail -n 1 | awk {'print $2'}`GB
              Swap: `free -g | tail -n 1 | awk {'print $2'}`GB
              Disk: `df -h / | awk '{ a = $2 } END { print a }'`
              Distro: `lsb_release -s -d` with `uname -r`

              CPU Load: `cat /proc/loadavg | awk '{print $1 ", " $2 ", " $3}'`
              Free Memory: `free -g | head -n 2 | tail -n 1 | awk {'print $4'}`GB
              Free Swap: `free -g | tail -n 1 | awk {'print $4'}`GB
              Free Disk: `df -h / | awk '{ a = $4 } END { print a }'`B
%                                                                                %
%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++%
EOF
